#import "../../fragments.gql"

query getFilterOptions {
  filterOptions @client {
    tagDelimiter
    forbiddenTags
  }
}

query getActiveFilters {
  activeFilters @client {
    ...CollectionProductOptionData
  }
}

query getFilteredProducts ($filter: [CollectionProductOption]!) {
  collectionProducts (filter: $filter) @client {
    handle
    title
    tags
    prices {
      min {
        value
        string
      }
      range
    }
    options {
      group
      value
    }
    featuredImage {
      alt
      lqip
      src
      srcset
    }
    images {
      alt
      lqip
      src
      srcset
    }
  }
}

mutation updateFilteredProducts ($filters: [FilterValues]!) {
  updateFilteredProducts (filters: $filters) @client
}
