fragment CollectionProductData on CollectionProduct {
  id
  handle
  title
  tags
  collections
  prices {
    min {
      value
      string
    }
    range
  }
  options {
    group
    value
  }
  featuredImage {
    alt
    lqip
    src
    srcset
  }
  images {
    alt
    lqip
    src
    srcset
  }
}

fragment CollectionProductImageData on CollectionProductImage {
  alt
  lqip
  src
  srcset
}

fragment CollectionProductOptionData on CollectionProductOption {
  group
  value
}

fragment CollectionProductPriceData on CollectionProductPrices {
  value
  string
}

fragment CollectionProductMetaData on CollectionProduct {
  handle
  title
  tags
}

fragment ProductInfo on Product {
  id
  handle
  title
  tags
  collections (first: 100) {
    edges {
      collection: node {
        handle
      }
    }
  }
  options(first: 3) {
    name
    values
  }
  prices: priceRange {
    ...PriceValues
  }
  images(first: 25) {
    edges {
      image: node {
        ...ImageSrc
      }
    }
  }
}


fragment PriceValues on ProductPriceRange {
  min: minVariantPrice {
    value: amount
  }
  max: maxVariantPrice {
    value: amount
  }
}

fragment ProductPrices on Prices {
  min {
    value
    string
  }
  range
}

fragment ImageSrc on Image {
  alt: altText
  lqip: transformedSrc(maxWidth: 40 preferredContentType: JPG scale: 1)
  src: transformedSrc(maxWidth: 400 preferredContentType: JPG scale: 1)
  src2x: transformedSrc(maxWidth: 400 preferredContentType: JPG scale: 2)
  src3x: transformedSrc(maxWidth: 400 preferredContentType: JPG scale: 3)
}

fragment ProductImage on Image {
  alt
  lqip
  src
  srcset
}
